[tox]
envlist = py310, py311, py312, py313, py314


[testenv]
deps =
    pytest
    pytest-cov
commands =
;    pip install --upgrade --no-cache-dir pip
    pytest --cov=api --cov=core --cov=models --cov=units --cov=utils tests/unit tests/integration
